[tools]
go = "1"
node = "lts"
rust = "stable"

aube = "latest"
bun = "latest"
uv = "latest"

github-cli = "latest"

bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
ghq = "latest"
ripgrep = "latest"

doggo = "latest"
jq = "latest"

[settings]
experimental = true

[settings.node]
compile = false

[settings.python]
compile = false
