[tools]
go = "1"
node = "lts"
rust = "stable"

bun = "latest"
uv = "latest"

github-cli = "latest"

bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
ghq = "latest"
ripgrep = "latest"

doggo = "latest"
jq = "latest"
"npm:obsidian-headless"  = "latest"
"github:trasta298/keifu" = "latest"
"github:k1LoW/mo" = "latest"

[settings]
experimental = true

[settings.node]
compile = false

[settings.python]
compile = false
